Webpage/main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

app_name = "main"   

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register", views.register, name="register"), #add registeration
    path("login", views.login_request, name ="login"), # add login function
    path("logout", views.logout_request, name= "logout"), # add logout function 
    path("upload",views.upload_file,name="upload" ),
    path("aboutus", views.about_us, name= "aboutus"), # add About us page
    path("data", views.data, name= "data"),
    path("data_analysis", views.data_analysis, name= "data_analysis"),
    path("data_analysis", views.data_analysis2, name= "data_analysis"),
    #path("data_prediction", views.data_prediction, name= "data_prediction"),
    path("contact_us", views.contact_us,name="contact_us" ),
    path("ubi_insurance", views.ubi,name="ubi_insurance" ),
    path("ubi_prediction", views.ubi_prediction,name="ubi_prediction" ),

]+ static(settings.MEDIA_URL,document_roots=settings.MEDIA_ROOT )

Webpage/mysite/urls.py
from django.contrib import admin
from django.urls import path, include  #add include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main.urls')), #add this
]

Webpage/main/models.py
from django.db import models
from django.contrib.auth.models import User # add user portfolio page
from django.dispatch import receiver # svae file
from django.db.models.signals import post_save # save file
from . import storage
from bson.objectid import ObjectId
# Create your models here.
class Profile(models.Model):   
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	@receiver(post_save, sender=User) #add this to save file
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

	@receiver(post_save, sender=User) #add this to save file
	def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()

	
class UploadFile(models.Model):
	title = models.CharField(max_length=50)
	file = models.FileField(upload_to='./filesupload', storage=storage.FieldStorage())
	dateTimeOfUpload = models.DateTimeField(auto_now = True)

class Contact(models.Model):
	email = models.EmailField()
	subject = models.CharField(max_length=255)
	message = models.TextField()

	def __str__(self):
		return self.email

#class File(models.Model):
	#date_time= models.DateTimeField()
	#Average_fuel_consumption = models.FloatField()
	#Average_speed = models.FloatField()
	#Distance_travelled = models.FloatField()
	#Engine_RPM = models.FloatField()
	#Fuel_used = models.FloatField()
	#Vehicle_speed = models.FloatField()

class File(models.Model):
	Date = models.DateTimeField()
	Distance_travelled = models.FloatField()
	Average_EngineRPM = models.IntegerField()
	Fuel_used = models.FloatField()
	Average_Vehiclespeed =  models.FloatField()
	Driver_Risk = models.IntegerField()

class DatePicker(models.Model):
    date = models.DateField()

Webpage/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Contact, DatePicker, Profile # add this for user profile

# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
	class Meta: 
		model = Profile
		fields = ('user',)

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = '__all__'


class UploadFileForm(forms.Form):
	title = forms.CharField(max_length=50)
	file = forms.FileField()

class FileForm(forms.Form):
	id = forms.IntegerField()
	Date = forms.DateTimeField()
	Distance_travelled = forms.FloatField()
	Average_EngineRPM = forms.IntegerField()
	Fuel_used = forms.FloatField()
	Average_Vehiclespeed =  forms.FloatField()
	Driver_Risk = forms.IntegerField()

class DateInput(forms.DateInput):
    input_type = 'date'

class DatePickerForm(forms.ModelForm):

    class Meta:
        model = DatePicker
        fields = [ 'date']
        widgets = {
            'date': DateInput(),
        }

Webpage/main/views.py
# Create your views here.
import io
from django.shortcuts import render, redirect
from .utils import get_db_handle, get_collection_handle
from django.contrib import messages #import messages
from django.contrib.auth import login, authenticate, logout #import authenticate
from django.contrib.auth.forms import AuthenticationForm #import AuthenticationForm
from .forms import * 
from .models import *
import pandas as pd
import glob, os
from os import listdir
import json
import pymongo
from pandas import DataFrame
from pyecharts import options as opts

db_handle, mongo_client = get_db_handle('CarCare_DB', 'localhost', 27017, 'USERNAME', 'PASSWORD')
collection_handle = get_collection_handle(db_handle, 'REGIONS_COLLECTION')
conn = pymongo.MongoClient("mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false")
db = conn["CarCare_DB"]

def homepage(request):
	return render(request = request, template_name="./home.html")

def about_us(request):
	return render(request = request, template_name="main/aboutus.html"	)

def contact_us(request):
	context = {}
	if request.method =='POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, "Sumbit successful." )
	form = ContactForm()
	context = {'form':form }
	return render(request = request, template_name="main/contact_us.html")

def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	
	return render(request=request, template_name="main/login.html", context={"form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("main:homepage")


def upload_file(request):
	context = {}

	if request.method == 'POST':
		form = UploadFileForm(request.POST,request.FILES)
		if form.is_valid():
			title = form.cleaned_data['title']
			file = form.cleaned_data['file']

			uploadfile = UploadFile()
			uploadfile.title = title
			uploadfile.file = file
			uploadfile.save()

		messages.info(request, "You have successfully uplaod file.")
		files = UploadFile.objects.values()
		files_pandas = pd.DataFrame(files)

	else:
		form = UploadFileForm()
	context['form'] = form
	
	return render(request,'main/upload.html',context={'form':form})

def data(request):
	files_path = 'C:/Users/USER/Desktop/code/env/mysite/static/files/filesupload'
	read_files = glob.glob(os.path.join(files_path,"*.csv"))

	np_array_values = []
	for files in read_files:
		data = pd.read_csv(files)
		np_array_values.append(data)
		print(files)

	with open("C:/Users/USER/Desktop/code/env/mysite/main/data/info.json","r") as file:
		JsonFile = json.load(file)
		client = pymongo.MongoClient()
		database = client[JsonFile["database"]]
		collection = database[JsonFile["collection"]]
		files = listdir(JsonFile["filePath"])

		for file in range(len(files)):

			fileName = JsonFile["filePath"]+"\\"+files[file]
			csvFile = pd.read_csv(fileName)
    
			[x,y] = csvFile.shape
			columns = list(csvFile.columns)
			data = csvFile.values
    
			for row in range(x):
				dataRow = data[row]
				DataDict = dict(zip(columns, dataRow))
				collection.insert(DataDict)
				
			print("Data has been inserted")

			# delete already read files
			os.remove(os.path.join(files_path, fileName))
		
		col = db["main_file"]
		if request.method == "POST":
			startdate = request.POST.get('startdate')
			enddate = request.POST.get('enddate')
			result = col.find({'date_time':{'$gte' : startdate, '$lte' : enddate}})
			return render(request,'main/data.html',{"data":result})
		else:
			file = File.objects.all()

		return render(request, 'main/data.html',{"data":file})

# reference: https://www.fooish.com/html/hyperlink-a-tag.html
def data_analysis(request):
	form = DatePickerForm(request.POST)
	if form.is_valid():
		date = form.cleaned_data['date']
		datepicker = DatePicker()
		datepicker.date = date
		datepicker.save()

		date = request.POST.get('date')
		if date == '2021-09-30':

			return render(request, "main/data_analysis.html", {'form':form})

	return render(request, "main/data_analysis2.html", {'form':form})

def data_analysis2(request):
	form = DatePickerForm(request.POST)
	if form.is_valid():
		date = form.cleaned_data['date']
		datepicker = DatePicker()
		datepicker.date = date
		datepicker.save()

		date = request.POST.get('date')
		if date == '2021-09-30':
		
			return render(request, "main/data_analysis.html", {'form':form})

	return render(request, "main/data_analysis2.html", {'form':form})

# def data_prediction(request):
	
# 	return render(request=request, template_name="main/data_prediction.html")	

def ubi(request):
	col = db.main_file
	data = col.find()
	list_data = list(data)
	# Converting to the DataFrame
	df = DataFrame(list_data)
	# print(df['Distance_travelled'])
	data = round(sum(df['Distance_travelled']), 2)
	return render(request, "main/ubi.html", {"data":data})

def ubi_prediction(request):

	return render(request, "main/ubi_prediction.html")

Webpage/main/templates/main/aboutus.html
{% extends "main/header.html" %}
{% load static %}
{% block content %}

<div class="bg-light py-4">
  <div class="container py-4">
    <div class="row mb-3">
      <div class="col-lg-4">
        <h2 class="display-4 font-weight-light">Advisor</h2>
    </div>
  </div>


	 <div class="row text-center">
      <!-- Team item-->
      <div class="col-xl-6 col-sm-5 mb-4">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="./static/images/david.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">David C. Li</h5><span class="text-uppercase text-muted">Advisor</span>
          <h5 class="mb-0"></h5><span class="text-muted">Email: davidli@mail.mcu.edu.tw</span>
        </div>
      </div>
      <!-- End-->
 <div class="bg-light py-2">
  <div class="container py-2">
    <div class="row mb-1">
      <div class="col-lg-4">
        <h2 class="display-4 font-weight-light">Our Team</h2>
      </div>
    </div>

    <div class="row text-center">
      <!-- Team item-->
      <div class="col-xl-6 col-sm-5 mb-4">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="./static/images/hansel.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Dick Hansel Ryan</h5><span class="text-uppercase text-muted">Project Manager</span>
		  <h5 class="mb-0"></h5><span class=" text-uppercase text-muted">Data Analyst</span>
      <h5 class="mb-0"></h5><span class="text-muted">Email: 07470136@me.mcu.edu.tw</span>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-6 col-sm-5 mb-4">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="./static/images/joyce.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">YI-JIE, TANG</h5><span class=" text-uppercase text-muted">Web Designer</span>
		  <h5 class="mb-0"></h5><span class=" text-uppercase text-muted">Database Manager</span>
      <h5 class="mb-0"></h5><span class="text-muted">Email: 07160113@me.mcu.edu.tw</span>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-6 col-sm-5 mb-4">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="./static/images/allen.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">REN-HE, WANG</h5><span class=" text-uppercase text-muted">Web Designer</span>
		  <h5 class="mb-0"></h5><span class=" text-uppercase text-muted">Data Collector</span>
      <h5 class="mb-0"></h5><span class="text-muted">Email: 07360612@me.mcu.edu.tw</span>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-6 col-sm-5 mb-4">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="./static/images/jane.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">CHEN, TUNG</h5><span class=" text-uppercase text-muted">UX / UI Designer</span>
		  <h5 class="mb-0"></h5><span class=" text-uppercase text-muted">Data Analyst</span>
      <h5 class="mb-0"></h5><span class="text-muted">Email: 07160122@me.mcu.edu.tw</span>
        </div>
      </div>
      <!-- End-->

    </div>
  </div>
</div>

	
{% endblock %}

Webpage/main/templates/main/contact_us.html
{% extends "main/header.html" %}
    {% load static %}
	{% block content %}
	{% load crispy_forms_tags %}

	<!--User page HTML-->

<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
<div class="container py-5">
	    <h1 class="font-weight-bold">Contact us</h1>
	    <hr>
	    <br>
<form action="" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="yTF5g7ceTgkwsOimKxZpuV10DG4a1TWFwQ60pneu047lPvu6kTAlNYPfYEC9G8jq">
    <tr>
        <th>
            <label for="id_email">Email:</label>
        </th>
        <td>
            <input type="email" name="email" maxlength="254" required id="id_email">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_subject">Subject:</label>
        </th>
        <td>
            <input type="text" name="subject" maxlength="255" required id="id_subject">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_message">Message:</label>
        </th>
        <td>
            <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
        </td>
    </tr>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

Webpage/main/templates/main/data.html
{% extends "main/header.html" %}

	{% block content %}

	<!--User page HTML-->
<br><br>
	<div class="container mx-auto">
	<meta name="viewport" content="width=device-width, initial-scale=1">
		    <div class="col-sm-12 col-md-12 col-lg-9 pb-4">
		    	<div class="col-6 my-auto">
		    	<h2 class="font-weight-bold pt-4">Data</h2>
				<br>
				<table border="1">
				<table class="table", style=center>
  					<thead>
    				<tr>
						<th scope="col">Date</th>
      					<th scope="col">Distance travelled(km)</th>
      					<th scope="col">Average EngineRPM(rpm)</th>
						<th scope="col">Fuel used(L)</th>
      					<th scope="col">Average Vehicle speed(km/h)</th>
						<th scope="col">Driver Risk</th>
    				</tr>
					{%for result in data%}
					<tr>
						<td>{{result.Date}}</td>
						<td>{{result.Distance_travelled}}</td>
						<td>{{result.Average_EngineRPM}}</td>
						<td>{{result.Fuel_used}}</td>
						<td>{{result.Average_Vehiclespeed}}</td>
						<td>{{result.Driver_Risk}}</td>
					{% endfor %}						
  					</thead>
				</table>
			</div>
		
	</div>

{% endblock %}

Webpage/main/templates/main/data_analysis2.html
{% extends "main/header.html" %}

	{% block content %}
	{% load crispy_forms_tags %}

	<!--User page HTML-->
	<div class="container mx-auto">
	    	<div class="col-sm-12 col-md-12 col-lg-3 pb-4">
		  	</div>
		    		<h2 class="font-weight-bold pt-4">Data Analysis</h2>
					<form method="POST" style= "width:400px">
					{% csrf_token %}
					{{ form|crispy }}

					<button class="btn btn-primary" type="submit" style="position:absolute;left:850px;top:270px">Submit</button>
					
					</div>
					</form>
					<br>

	</div>
{% endblock %}

Webpage/main/templates/main/data_prediction.html
{% extends "main/header.html" %}

	{% block content %}
	{% load crispy_forms_tags %}

	<!--User page HTML-->
<br><br>
	<div class="container mx-auto">
	    	<div class="col-sm-12 col-md-12 col-lg-3 pb-4">
		  	</div>
		    		<div class="col-6 my-auto">
					<br>
					
		    			<h2 class="font-weight-bold pt-4">Data Prediction</h2>
		
		        </div>
		    </div> 
		</div>
	</div>
{% endblock %}

Webpage/main/templates/main/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
     <!-- Our project just needs Font Awesome Free's Solid + Brand files -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
  </head>
  <body>
    
    {% include 'main/includes/navbar.html' %}

    {% include 'main/includes/messages.html' %}

    {% block content %}


    {% endblock %} 

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

Webpage/main/templates/main/login.html
{% extends "main/header.html" %}

	{% block content %}

	{% load crispy_forms_tags %}   

	<!--Login--> 
	<div class="container py-5">
		<h1 class="font-weight-bold">Login</h1>
		<hr>
	    <br>
		<form method="POST">
			{% csrf_token %}
			{{ form|crispy }}
			<br>
			<button class="btn btn-primary" type="submit">Login</button>
		</form>
		<br><br>
	</div>

	{% endblock %}

Webpage/main/templates/main/register.html
{% extends "main/header.html" %}

	{% block content %}

	{% load crispy_forms_tags %}

	<!-- Register page HTML will go here-->
	<div class="container py-5">
	    <h1 class="font-weight-bold">Register</h1>
	    <hr>
	    <br>
		<form method="POST">
			{% csrf_token %}
			{{ form|crispy }} <!--add this for form-->                    
			<br>
			<button class="btn btn-primary" type="submit">Submit</button>
		</form>
		<br><br>
		<p>If you already have an account, <a href="/login">login</a> instead.</p>
	</div>

{% endblock %}

Webpage/main/templates/main/ubi.html
{% extends "main/header.html" %}

	{% block content %}
	{% load crispy_forms_tags %}

	<!--User page HTML-->
<br><br>
	<div class="container mx-auto">
		<div class="col align-self-start">
			<h2 class="display-6 font-weight-bold">UBI Introduction</h2>
			<br/> Usage-Based Insurance (UBI) is also known as pay as you drive (PAYD) and pay how you drive (PHYD)
			It's a policy that's priced based on everyone's "behavior."
			<br>Different drivers are given different premiums depending on their driving habits, making it fairer and more reasonable for safe drivers with low accident rates.
			<br>The cost depends on the type of vehicle used, depending on the time, distance, behavior and location.</br>
			<h2 class="font-weight-bold pt-4">UBI Insurance</h2>
			<br>
			<h4>Total Distance travelled: {{data}} km</h4>
			<br>
			<h4>Insurance fee: ${{fee}} NTD</h4>
			<br>

		</div>
	</div>
{% endblock %}

Webpage/main/templates/main/ubi_prediction.html
{% extends "main/header.html" %}

	{% block content %}
	{% load crispy_forms_tags %}

	<!--User page HTML-->
<br><br>
	<div class="container mx-auto">
		<div class="col align-self-start">
			<h2 class="display-6 font-weight-bold">UBI Prediction</h2>

			<br>

		</div>
	</div>
{% endblock %}

Webpage/main/templates/main/upload.html
{% extends "main/header.html" %}

    {% block content %}
    	<div class="container py-5">
		<h1 class="font-weight-bold">Upload data</h1>
		<form  method= "POST" enctype="multipart/form-data">
        	{% csrf_token %}
			{{ form.as_p }}

			<button class="btn btn-primary" type="submit">Upload</button>
			{{context}}
        </form>
		<hr>
		
		<br><br>
	</div>

{% endblock%}